version: '3.8'

services:


  springbased:
    build:
      context: ./spring
    container_name: spring
    ports:
      - "8081:8080"

  micronautbased_first:
    build:
      context: ./micronaut
    container_name: micro1
    ports:
      - "8082:8080"

  micronautbased_second:
    build:
      context: ./micronaut
    container_name: micro2
    ports:
      - "8083:8080"

  myzookeeper:
    image: zookeeper
    container_name: myzookeeper
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
      - "18080:8080"
#    environment:
#      ZOO_MY_ID: 1
#      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181